### ISSUE TITLE
add explicit "swipe mode" option in general settings

### ISSUE THREAD

**Issue by bryndyment** [hoologic/app.realkana#5]
- `Swipe Mode` (alphabetically, after `Slideshow Mode`)

**Comment by seancoady** [comment]
it's going to be weird with the animations for the slideshow stepper row with Swipe Mode below the stepper. How about if we use a single cell for Slideshow but dynamically resize it to expose/hide the stepper as it's selected/de-selected?

**Comment by bryndyment** [comment]
confused ... call if you can

**Comment by seancoady** [comment]
let's talk tomorrow, I'm beat. Right now when you select Slideshow, it
inserts a new cell below Slideshow that contains the stepper. When you
de-select Slideshow it removes the cell. "Swipe Mode" would need to be
adjusted up/down in its index. I'm proposing that instead of
inserting/deleting/moving cells and managing their indexes, we instead
always have three cells in that section, with the Slideshow cell being
adjustable in height to show/hide the stepper.

**Comment by bryndyment** [comment]
sounds like an implementation detail ... sounds good

**Comment by bryndyment** [comment]
(removing: make `Keyboard Mode` the default initial value ... keep as swipe mode)

**Comment by bryndyment** [comment]
Don't really like the flashing that occurs when you tap `Slideshow Mode` ... is there a better way to implement?

**Comment by bryndyment** [comment]
kinda wonky

**Comment by seancoady** [comment]
try this instead

**Comment by bryndyment** [comment]
still looks like a bug :(

**Comment by seancoady** [comment]
one more (give it a try)

**Comment by bryndyment** [comment]
:+1:
